
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ir.imi.testwebcard.domain.soap;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-01-08T14:55:53.942+03:30
 * Generated source version: 3.6.5
 *
 */

@javax.jws.WebService(
                      serviceName = "EtsGeneralDataProviderService",
                      portName = "EtsGeneralDataProviderServiceSoap12",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "file:/C:/Users/O120F~1.ASH/AppData/Local/Temp/tempdir15051163935329490852.tmp/EtsGeneralDataProviderService_1.wsdl",
                      endpointInterface = "ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap")

public class EtsGeneralDataProviderServiceSoap12Impl implements EtsGeneralDataProviderServiceSoap {

    private static final Logger LOG = Logger.getLogger(EtsGeneralDataProviderServiceSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addSpecialExtraWorkPermission(java.lang.String employeeCode, int value, long periodId, java.lang.String requestReason, java.lang.String description, long specialExtraWorkId, long organizationChartId)*
     */
    public java.lang.String addSpecialExtraWorkPermission(java.lang.String employeeCode, int value, long periodId, java.lang.String requestReason, java.lang.String description, long specialExtraWorkId, long organizationChartId) {
        LOG.info("Executing operation addSpecialExtraWorkPermission");
        System.out.println(employeeCode);
        System.out.println(value);
        System.out.println(periodId);
        System.out.println(requestReason);
        System.out.println(description);
        System.out.println(specialExtraWorkId);
        System.out.println(organizationChartId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addMissionRegistrationPermission(java.lang.String employeeCode, long missionId, long missionLocationId, java.lang.String missionSubject, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String requestReason, java.lang.String description)*
     */
    public java.lang.String addMissionRegistrationPermission(java.lang.String employeeCode, long missionId, long missionLocationId, java.lang.String missionSubject, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String requestReason, java.lang.String description) {
        LOG.info("Executing operation addMissionRegistrationPermission");
        System.out.println(employeeCode);
        System.out.println(missionId);
        System.out.println(missionLocationId);
        System.out.println(missionSubject);
        System.out.println(beginDateTime);
        System.out.println(endDateTime);
        System.out.println(requestReason);
        System.out.println(description);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#isValidPersonStringDate(java.lang.String employeeCode, java.lang.String dateTime, int requestState)*
     */
    public boolean isValidPersonStringDate(java.lang.String employeeCode, java.lang.String dateTime, int requestState) {
        LOG.info("Executing operation isValidPersonStringDate");
        System.out.println(employeeCode);
        System.out.println(dateTime);
        System.out.println(requestState);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#test()*
     */
    public java.lang.String test() {
        LOG.info("Executing operation test");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getIORecordPerPersistOn(java.lang.String fromDate, java.lang.String toDate)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getIORecordPerPersistOn(java.lang.String fromDate, java.lang.String toDate) {
        LOG.info("Executing operation getIORecordPerPersistOn");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getFunctionalityList(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfString getFunctionalityList(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation getFunctionalityList");
        System.out.println(employeeCode);
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addDailyExtraWorkPermission(java.lang.String employeeCode, long extraWorkId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String requestReason, java.lang.String description)*
     */
    public java.lang.String addDailyExtraWorkPermission(java.lang.String employeeCode, long extraWorkId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String requestReason, java.lang.String description) {
        LOG.info("Executing operation addDailyExtraWorkPermission");
        System.out.println(employeeCode);
        System.out.println(extraWorkId);
        System.out.println(beginDateTime);
        System.out.println(endDateTime);
        System.out.println(requestReason);
        System.out.println(description);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getFunctionalityWinPayList(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar date, boolean withVacation, boolean withSequenceWorkingDetails, boolean withSpecialExtraWork, boolean withVacationRemaining, boolean withSpecialAddSubVacation, boolean withMission)*
     */
    public ir.imi.testwebcard.domain.soap.PeriodCalculationInfo getFunctionalityWinPayList(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar date, boolean withVacation, boolean withSequenceWorkingDetails, boolean withSpecialExtraWork, boolean withVacationRemaining, boolean withSpecialAddSubVacation, boolean withMission) {
        LOG.info("Executing operation getFunctionalityWinPayList");
        System.out.println(employeeCode);
        System.out.println(date);
        System.out.println(withVacation);
        System.out.println(withSequenceWorkingDetails);
        System.out.println(withSpecialExtraWork);
        System.out.println(withVacationRemaining);
        System.out.println(withSpecialAddSubVacation);
        System.out.println(withMission);
        try {
            ir.imi.testwebcard.domain.soap.PeriodCalculationInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllCurrentlyEmployeesWithKey()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModelWithKey getAllCurrentlyEmployeesWithKey() {
        LOG.info("Executing operation getAllCurrentlyEmployeesWithKey");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModelWithKey _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getPeriodCalculationInfo(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public void getPeriodCalculationInfo(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation getPeriodCalculationInfo");
        System.out.println(employeeCode);
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#isValidReserve(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar startDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String officialHolidaySetting, java.lang.String agreedHolidaySetting, java.lang.String normalDaySetting, boolean chekExtraWorkPermission)*
     */
    public boolean isValidReserve(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar startDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String officialHolidaySetting, java.lang.String agreedHolidaySetting, java.lang.String normalDaySetting, boolean chekExtraWorkPermission) {
        LOG.info("Executing operation isValidReserve");
        System.out.println(employeeCode);
        System.out.println(startDateTime);
        System.out.println(endDateTime);
        System.out.println(officialHolidaySetting);
        System.out.println(agreedHolidaySetting);
        System.out.println(normalDaySetting);
        System.out.println(chekExtraWorkPermission);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#isValidPerson(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar dateTime, int requestState, java.lang.String leaveHour)*
     */
    public boolean isValidPerson(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar dateTime, int requestState, java.lang.String leaveHour) {
        LOG.info("Executing operation isValidPerson");
        System.out.println(employeeCode);
        System.out.println(dateTime);
        System.out.println(requestState);
        System.out.println(leaveHour);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getOrganizationChartIdByEmployeeById(long regionId, long employeeId)*
     */
    public java.lang.Long getOrganizationChartIdByEmployeeById(long regionId, long employeeId) {
        LOG.info("Executing operation getOrganizationChartIdByEmployeeById");
        System.out.println(regionId);
        System.out.println(employeeId);
        try {
            java.lang.Long _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllExtraWorkPermissionsByDate(java.lang.String date)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfDailyExtraWorkPermissionDataModel getAllExtraWorkPermissionsByDate(java.lang.String date) {
        LOG.info("Executing operation getAllExtraWorkPermissionsByDate");
        System.out.println(date);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfDailyExtraWorkPermissionDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getDailyMissionsOrVacations(javax.xml.datatype.XMLGregorianCalendar startDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime)*
     */
    public java.lang.String getDailyMissionsOrVacations(javax.xml.datatype.XMLGregorianCalendar startDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime) {
        LOG.info("Executing operation getDailyMissionsOrVacations");
        System.out.println(startDateTime);
        System.out.println(endDateTime);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllEmployeesInfo()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo getAllEmployeesInfo() {
        LOG.info("Executing operation getAllEmployeesInfo");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addMissionRegistration(java.lang.String employeeCode, long missionId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime)*
     */
    public java.lang.String addMissionRegistration(java.lang.String employeeCode, long missionId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime) {
        LOG.info("Executing operation addMissionRegistration");
        System.out.println(employeeCode);
        System.out.println(missionId);
        System.out.println(beginDateTime);
        System.out.println(endDateTime);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getIoSources()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfString getIoSources() {
        LOG.info("Executing operation getIoSources");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getEmployeeFullNameFromLoginResult(java.lang.String userName, java.lang.String password)*
     */
    public java.lang.String getEmployeeFullNameFromLoginResult(java.lang.String userName, java.lang.String password) {
        LOG.info("Executing operation getEmployeeFullNameFromLoginResult");
        System.out.println(userName);
        System.out.println(password);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getUiRequestCartableIds(java.lang.String employeeCode)*
     */
    public ir.imi.testwebcard.domain.soap.UiRequestCartableIds getUiRequestCartableIds(java.lang.String employeeCode) {
        LOG.info("Executing operation getUiRequestCartableIds");
        System.out.println(employeeCode);
        try {
            ir.imi.testwebcard.domain.soap.UiRequestCartableIds _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getCalendarWorkDayTypesByEmployee(java.lang.String employeeCode, java.lang.String fromDate, java.lang.String toDate)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto getCalendarWorkDayTypesByEmployee(java.lang.String employeeCode, java.lang.String fromDate, java.lang.String toDate) {
        LOG.info("Executing operation getCalendarWorkDayTypesByEmployee");
        System.out.println(employeeCode);
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllEmployeesWithOrgId()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo getAllEmployeesWithOrgId() {
        LOG.info("Executing operation getAllEmployeesWithOrgId");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllPeriodFunctionalityWinPayList(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar date, boolean withVacation, boolean withSequenceWorkingDetails, boolean withSpecialExtraWork, boolean withVacationRemaining, boolean withSpecialAddSubVacation, boolean withMission)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfPeriodCalculationInfo getAllPeriodFunctionalityWinPayList(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar date, boolean withVacation, boolean withSequenceWorkingDetails, boolean withSpecialExtraWork, boolean withVacationRemaining, boolean withSpecialAddSubVacation, boolean withMission) {
        LOG.info("Executing operation getAllPeriodFunctionalityWinPayList");
        System.out.println(employeeCode);
        System.out.println(date);
        System.out.println(withVacation);
        System.out.println(withSequenceWorkingDetails);
        System.out.println(withSpecialExtraWork);
        System.out.println(withVacationRemaining);
        System.out.println(withSpecialAddSubVacation);
        System.out.println(withMission);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfPeriodCalculationInfo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getOrganizationChartList(long regionId)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfString getOrganizationChartList(long regionId) {
        LOG.info("Executing operation getOrganizationChartList");
        System.out.println(regionId);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getValidCardList(long regionId)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfString getValidCardList(long regionId) {
        LOG.info("Executing operation getValidCardList");
        System.out.println(regionId);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllVacationRegistrationsByDate(java.lang.String date)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfVacationRegistrationDataModel getAllVacationRegistrationsByDate(java.lang.String date) {
        LOG.info("Executing operation getAllVacationRegistrationsByDate");
        System.out.println(date);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfVacationRegistrationDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId(long currentOrganizationchartId)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId(long currentOrganizationchartId) {
        LOG.info("Executing operation getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId");
        System.out.println(currentOrganizationchartId);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllMissionRegistrationsByDate(java.lang.String date)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfMissionRegistrationDataModel getAllMissionRegistrationsByDate(java.lang.String date) {
        LOG.info("Executing operation getAllMissionRegistrationsByDate");
        System.out.println(date);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfMissionRegistrationDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getIoRecordInDayByEmployeeCode(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar dayDate)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfStaffIOs getIoRecordInDayByEmployeeCode(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar dayDate) {
        LOG.info("Executing operation getIoRecordInDayByEmployeeCode");
        System.out.println(employeeCode);
        System.out.println(dayDate);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfStaffIOs _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#checkTimeAttendanceSystemHasThirdPartyWebServicec()*
     */
    public boolean checkTimeAttendanceSystemHasThirdPartyWebServicec() {
        LOG.info("Executing operation checkTimeAttendanceSystemHasThirdPartyWebServicec");
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllOrganizationChartList()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel getAllOrganizationChartList() {
        LOG.info("Executing operation getAllOrganizationChartList");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllEmployees()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getAllEmployees() {
        LOG.info("Executing operation getAllEmployees");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getRemainUiEmployeeVacationTypeRepositoryList(java.lang.String employeeCode, long currentWorkingYear)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfString getRemainUiEmployeeVacationTypeRepositoryList(java.lang.String employeeCode, long currentWorkingYear) {
        LOG.info("Executing operation getRemainUiEmployeeVacationTypeRepositoryList");
        System.out.println(employeeCode);
        System.out.println(currentWorkingYear);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllSpecialExtraWorksByPeriodId(long periodId)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfSpecialExtraWorkDataModel getAllSpecialExtraWorksByPeriodId(long periodId) {
        LOG.info("Executing operation getAllSpecialExtraWorksByPeriodId");
        System.out.println(periodId);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfSpecialExtraWorkDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getEmployeeCodeByKeyNumber(java.lang.String keyNumber, java.lang.String gregorianDate, java.lang.String shamsiDate, ir.imi.testwebcard.domain.soap.SystemModuleType systemType, ir.imi.testwebcard.domain.soap.UiDeviceModuleType deviceModuleType)*
     */
    public java.lang.String getEmployeeCodeByKeyNumber(java.lang.String keyNumber, java.lang.String gregorianDate, java.lang.String shamsiDate, ir.imi.testwebcard.domain.soap.SystemModuleType systemType, ir.imi.testwebcard.domain.soap.UiDeviceModuleType deviceModuleType) {
        LOG.info("Executing operation getEmployeeCodeByKeyNumber");
        System.out.println(keyNumber);
        System.out.println(gregorianDate);
        System.out.println(shamsiDate);
        System.out.println(systemType);
        System.out.println(deviceModuleType);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getIsExitOverTimeList(java.lang.String perno, java.lang.String time, javax.xml.datatype.XMLGregorianCalendar startDate, javax.xml.datatype.XMLGregorianCalendar endDate)*
     */
    public boolean getIsExitOverTimeList(java.lang.String perno, java.lang.String time, javax.xml.datatype.XMLGregorianCalendar startDate, javax.xml.datatype.XMLGregorianCalendar endDate) {
        LOG.info("Executing operation getIsExitOverTimeList");
        System.out.println(perno);
        System.out.println(time);
        System.out.println(startDate);
        System.out.println(endDate);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getOrganizationChartIdByEmployee(long regionId, long employeeId)*
     */
    public long getOrganizationChartIdByEmployee(long regionId, long employeeId) {
        LOG.info("Executing operation getOrganizationChartIdByEmployee");
        System.out.println(regionId);
        System.out.println(employeeId);
        try {
            long _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getDayCalculationInfo(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate)*
     */
    public void getDayCalculationInfo(java.lang.String employeeCode, javax.xml.datatype.XMLGregorianCalendar fromDate, javax.xml.datatype.XMLGregorianCalendar toDate) {
        LOG.info("Executing operation getDayCalculationInfo");
        System.out.println(employeeCode);
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getListOfEmployeeEvents(ir.imi.testwebcard.domain.soap.EmployeeEventType employeeEvent)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getListOfEmployeeEvents(ir.imi.testwebcard.domain.soap.EmployeeEventType employeeEvent) {
        LOG.info("Executing operation getListOfEmployeeEvents");
        System.out.println(employeeEvent);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addVacationRegistration(java.lang.String employeeCode, long vacationId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime)*
     */
    public java.lang.String addVacationRegistration(java.lang.String employeeCode, long vacationId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime) {
        LOG.info("Executing operation addVacationRegistration");
        System.out.println(employeeCode);
        System.out.println(vacationId);
        System.out.println(beginDateTime);
        System.out.println(endDateTime);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllCurrentlyEmployees()*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getAllCurrentlyEmployees() {
        LOG.info("Executing operation getAllCurrentlyEmployees");
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllEmployeesOfOneOrganizationChartWithAllSubsets(long currentOrganizationchartId)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getAllEmployeesOfOneOrganizationChartWithAllSubsets(long currentOrganizationchartId) {
        LOG.info("Executing operation getAllEmployeesOfOneOrganizationChartWithAllSubsets");
        System.out.println(currentOrganizationchartId);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getIORecordAfterId(long id)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getIORecordAfterId(long id) {
        LOG.info("Executing operation getIORecordAfterId");
        System.out.println(id);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#isPresent(long id, javax.xml.datatype.XMLGregorianCalendar dateTime)*
     */
    public boolean isPresent(long id, javax.xml.datatype.XMLGregorianCalendar dateTime) {
        LOG.info("Executing operation isPresent");
        System.out.println(id);
        System.out.println(dateTime);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getDevicePersons(java.util.List<java.lang.String> deviceModuleType)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfDevicePerson getDevicePersons(java.util.List<java.lang.String> deviceModuleType) {
        LOG.info("Executing operation getDevicePersons");
        System.out.println(deviceModuleType);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfDevicePerson _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllIoRecordsByDate(java.lang.String date)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getAllIoRecordsByDate(java.lang.String date) {
        LOG.info("Executing operation getAllIoRecordsByDate");
        System.out.println(date);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getUiRequestCartableCount(java.lang.String employeeCode)*
     */
    public java.lang.String getUiRequestCartableCount(java.lang.String employeeCode) {
        LOG.info("Executing operation getUiRequestCartableCount");
        System.out.println(employeeCode);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getRemainUiEmployeeVacationTypeRepository(java.lang.String employeeCode, long vacationtypeId)*
     */
    public java.lang.String getRemainUiEmployeeVacationTypeRepository(java.lang.String employeeCode, long vacationtypeId) {
        LOG.info("Executing operation getRemainUiEmployeeVacationTypeRepository");
        System.out.println(employeeCode);
        System.out.println(vacationtypeId);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getAllValidEmployeeRange(javax.xml.datatype.XMLGregorianCalendar dateTime, int requestState)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfValidEmployeeRange getAllValidEmployeeRange(javax.xml.datatype.XMLGregorianCalendar dateTime, int requestState) {
        LOG.info("Executing operation getAllValidEmployeeRange");
        System.out.println(dateTime);
        System.out.println(requestState);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfValidEmployeeRange _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getIORecordPerDateRange(java.lang.String fromDate, java.lang.String toDate)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getIORecordPerDateRange(java.lang.String fromDate, java.lang.String toDate) {
        LOG.info("Executing operation getIORecordPerDateRange");
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getCalendarWorkDayTypes(java.lang.String calendarName, java.lang.String fromDate, java.lang.String toDate)*
     */
    public ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto getCalendarWorkDayTypes(java.lang.String calendarName, java.lang.String fromDate, java.lang.String toDate) {
        LOG.info("Executing operation getCalendarWorkDayTypes");
        System.out.println(calendarName);
        System.out.println(fromDate);
        System.out.println(toDate);
        try {
            ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addMissionRegistrationEx(java.lang.String employeeCode, java.lang.String confirmEmployeeCode, long missionId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String missionLocationName)*
     */
    public java.lang.String addMissionRegistrationEx(java.lang.String employeeCode, java.lang.String confirmEmployeeCode, long missionId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String missionLocationName) {
        LOG.info("Executing operation addMissionRegistrationEx");
        System.out.println(employeeCode);
        System.out.println(confirmEmployeeCode);
        System.out.println(missionId);
        System.out.println(beginDateTime);
        System.out.println(endDateTime);
        System.out.println(missionLocationName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#addVacationRegistrationPermission(java.lang.String employeeCode, long vacationId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String vacationRequestReason, java.lang.String description)*
     */
    public java.lang.String addVacationRegistrationPermission(java.lang.String employeeCode, long vacationId, javax.xml.datatype.XMLGregorianCalendar beginDateTime, javax.xml.datatype.XMLGregorianCalendar endDateTime, java.lang.String vacationRequestReason, java.lang.String description) {
        LOG.info("Executing operation addVacationRegistrationPermission");
        System.out.println(employeeCode);
        System.out.println(vacationId);
        System.out.println(beginDateTime);
        System.out.println(endDateTime);
        System.out.println(vacationRequestReason);
        System.out.println(description);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#persistIoRecrd(java.lang.String keyNumber, javax.xml.datatype.XMLGregorianCalendar ioDateTime, long deviceModuleType, long hadwareCode)*
     */
    public boolean persistIoRecrd(java.lang.String keyNumber, javax.xml.datatype.XMLGregorianCalendar ioDateTime, long deviceModuleType, long hadwareCode) {
        LOG.info("Executing operation persistIoRecrd");
        System.out.println(keyNumber);
        System.out.println(ioDateTime);
        System.out.println(deviceModuleType);
        System.out.println(hadwareCode);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ir.imi.testwebcard.domain.soap.EtsGeneralDataProviderServiceSoap#getTimeAttendancePcCheckByEmployeeCode(java.lang.String employeeCode, java.lang.String dateTime, java.lang.Boolean getTimeAttendancePcCheckByEmployeeCodeResult, java.lang.String reason)*
     */
    public void getTimeAttendancePcCheckByEmployeeCode(java.lang.String employeeCode, java.lang.String dateTime, javax.xml.ws.Holder<java.lang.Boolean> getTimeAttendancePcCheckByEmployeeCodeResult, javax.xml.ws.Holder<java.lang.String> reason) {
        LOG.info("Executing operation getTimeAttendancePcCheckByEmployeeCode");
        System.out.println(employeeCode);
        System.out.println(dateTime);
        try {
            java.lang.Boolean getTimeAttendancePcCheckByEmployeeCodeResultValue = null;
            getTimeAttendancePcCheckByEmployeeCodeResult.value = getTimeAttendancePcCheckByEmployeeCodeResultValue;
            java.lang.String reasonValue = "";
            reason.value = reasonValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
