
package ir.imi.testwebcard.domain.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-01-08T14:55:53.801+03:30
 * Generated source version: 3.6.5
 *
 */
public final class EtsGeneralDataProviderServiceSoap_EtsGeneralDataProviderServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "EtsGeneralDataProviderService");

    private EtsGeneralDataProviderServiceSoap_EtsGeneralDataProviderServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EtsGeneralDataProviderService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EtsGeneralDataProviderService ss = new EtsGeneralDataProviderService(wsdlURL, SERVICE_NAME);
        EtsGeneralDataProviderServiceSoap port = ss.getEtsGeneralDataProviderServiceSoap();

        {
        System.out.println("Invoking addSpecialExtraWorkPermission...");
        java.lang.String _addSpecialExtraWorkPermission_employeeCode = "";
        int _addSpecialExtraWorkPermission_value = 0;
        long _addSpecialExtraWorkPermission_periodId = 0;
        java.lang.String _addSpecialExtraWorkPermission_requestReason = "";
        java.lang.String _addSpecialExtraWorkPermission_description = "";
        long _addSpecialExtraWorkPermission_specialExtraWorkId = 0;
        long _addSpecialExtraWorkPermission_organizationChartId = 0;
        java.lang.String _addSpecialExtraWorkPermission__return = port.addSpecialExtraWorkPermission(_addSpecialExtraWorkPermission_employeeCode, _addSpecialExtraWorkPermission_value, _addSpecialExtraWorkPermission_periodId, _addSpecialExtraWorkPermission_requestReason, _addSpecialExtraWorkPermission_description, _addSpecialExtraWorkPermission_specialExtraWorkId, _addSpecialExtraWorkPermission_organizationChartId);
        System.out.println("addSpecialExtraWorkPermission.result=" + _addSpecialExtraWorkPermission__return);


        }
        {
        System.out.println("Invoking addMissionRegistrationPermission...");
        java.lang.String _addMissionRegistrationPermission_employeeCode = "";
        long _addMissionRegistrationPermission_missionId = 0;
        long _addMissionRegistrationPermission_missionLocationId = 0;
        java.lang.String _addMissionRegistrationPermission_missionSubject = "";
        javax.xml.datatype.XMLGregorianCalendar _addMissionRegistrationPermission_beginDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addMissionRegistrationPermission_endDateTime = null;
        java.lang.String _addMissionRegistrationPermission_requestReason = "";
        java.lang.String _addMissionRegistrationPermission_description = "";
        java.lang.String _addMissionRegistrationPermission__return = port.addMissionRegistrationPermission(_addMissionRegistrationPermission_employeeCode, _addMissionRegistrationPermission_missionId, _addMissionRegistrationPermission_missionLocationId, _addMissionRegistrationPermission_missionSubject, _addMissionRegistrationPermission_beginDateTime, _addMissionRegistrationPermission_endDateTime, _addMissionRegistrationPermission_requestReason, _addMissionRegistrationPermission_description);
        System.out.println("addMissionRegistrationPermission.result=" + _addMissionRegistrationPermission__return);


        }
        {
        System.out.println("Invoking isValidPersonStringDate...");
        java.lang.String _isValidPersonStringDate_employeeCode = "";
        java.lang.String _isValidPersonStringDate_dateTime = "";
        int _isValidPersonStringDate_requestState = 0;
        boolean _isValidPersonStringDate__return = port.isValidPersonStringDate(_isValidPersonStringDate_employeeCode, _isValidPersonStringDate_dateTime, _isValidPersonStringDate_requestState);
        System.out.println("isValidPersonStringDate.result=" + _isValidPersonStringDate__return);


        }
        {
        System.out.println("Invoking test...");
        java.lang.String _test__return = port.test();
        System.out.println("test.result=" + _test__return);


        }
        {
        System.out.println("Invoking getIORecordPerPersistOn...");
        java.lang.String _getIORecordPerPersistOn_fromDate = "";
        java.lang.String _getIORecordPerPersistOn_toDate = "";
        ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _getIORecordPerPersistOn__return = port.getIORecordPerPersistOn(_getIORecordPerPersistOn_fromDate, _getIORecordPerPersistOn_toDate);
        System.out.println("getIORecordPerPersistOn.result=" + _getIORecordPerPersistOn__return);


        }
        {
        System.out.println("Invoking getFunctionalityList...");
        java.lang.String _getFunctionalityList_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getFunctionalityList_fromDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getFunctionalityList_toDate = null;
        ir.imi.testwebcard.domain.soap.ArrayOfString _getFunctionalityList__return = port.getFunctionalityList(_getFunctionalityList_employeeCode, _getFunctionalityList_fromDate, _getFunctionalityList_toDate);
        System.out.println("getFunctionalityList.result=" + _getFunctionalityList__return);


        }
        {
        System.out.println("Invoking addDailyExtraWorkPermission...");
        java.lang.String _addDailyExtraWorkPermission_employeeCode = "";
        long _addDailyExtraWorkPermission_extraWorkId = 0;
        javax.xml.datatype.XMLGregorianCalendar _addDailyExtraWorkPermission_beginDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addDailyExtraWorkPermission_endDateTime = null;
        java.lang.String _addDailyExtraWorkPermission_requestReason = "";
        java.lang.String _addDailyExtraWorkPermission_description = "";
        java.lang.String _addDailyExtraWorkPermission__return = port.addDailyExtraWorkPermission(_addDailyExtraWorkPermission_employeeCode, _addDailyExtraWorkPermission_extraWorkId, _addDailyExtraWorkPermission_beginDateTime, _addDailyExtraWorkPermission_endDateTime, _addDailyExtraWorkPermission_requestReason, _addDailyExtraWorkPermission_description);
        System.out.println("addDailyExtraWorkPermission.result=" + _addDailyExtraWorkPermission__return);


        }
        {
        System.out.println("Invoking getFunctionalityWinPayList...");
        java.lang.String _getFunctionalityWinPayList_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getFunctionalityWinPayList_date = null;
        boolean _getFunctionalityWinPayList_withVacation = false;
        boolean _getFunctionalityWinPayList_withSequenceWorkingDetails = false;
        boolean _getFunctionalityWinPayList_withSpecialExtraWork = false;
        boolean _getFunctionalityWinPayList_withVacationRemaining = false;
        boolean _getFunctionalityWinPayList_withSpecialAddSubVacation = false;
        boolean _getFunctionalityWinPayList_withMission = false;
        ir.imi.testwebcard.domain.soap.PeriodCalculationInfo _getFunctionalityWinPayList__return = port.getFunctionalityWinPayList(_getFunctionalityWinPayList_employeeCode, _getFunctionalityWinPayList_date, _getFunctionalityWinPayList_withVacation, _getFunctionalityWinPayList_withSequenceWorkingDetails, _getFunctionalityWinPayList_withSpecialExtraWork, _getFunctionalityWinPayList_withVacationRemaining, _getFunctionalityWinPayList_withSpecialAddSubVacation, _getFunctionalityWinPayList_withMission);
        System.out.println("getFunctionalityWinPayList.result=" + _getFunctionalityWinPayList__return);


        }
        {
        System.out.println("Invoking getAllCurrentlyEmployeesWithKey...");
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModelWithKey _getAllCurrentlyEmployeesWithKey__return = port.getAllCurrentlyEmployeesWithKey();
        System.out.println("getAllCurrentlyEmployeesWithKey.result=" + _getAllCurrentlyEmployeesWithKey__return);


        }
        {
        System.out.println("Invoking getPeriodCalculationInfo...");
        java.lang.String _getPeriodCalculationInfo_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getPeriodCalculationInfo_fromDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getPeriodCalculationInfo_toDate = null;
        port.getPeriodCalculationInfo(_getPeriodCalculationInfo_employeeCode, _getPeriodCalculationInfo_fromDate, _getPeriodCalculationInfo_toDate);


        }
        {
        System.out.println("Invoking isValidReserve...");
        java.lang.String _isValidReserve_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _isValidReserve_startDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _isValidReserve_endDateTime = null;
        java.lang.String _isValidReserve_officialHolidaySetting = "";
        java.lang.String _isValidReserve_agreedHolidaySetting = "";
        java.lang.String _isValidReserve_normalDaySetting = "";
        boolean _isValidReserve_chekExtraWorkPermission = false;
        boolean _isValidReserve__return = port.isValidReserve(_isValidReserve_employeeCode, _isValidReserve_startDateTime, _isValidReserve_endDateTime, _isValidReserve_officialHolidaySetting, _isValidReserve_agreedHolidaySetting, _isValidReserve_normalDaySetting, _isValidReserve_chekExtraWorkPermission);
        System.out.println("isValidReserve.result=" + _isValidReserve__return);


        }
        {
        System.out.println("Invoking isValidPerson...");
        java.lang.String _isValidPerson_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _isValidPerson_dateTime = null;
        int _isValidPerson_requestState = 0;
        java.lang.String _isValidPerson_leaveHour = "";
        boolean _isValidPerson__return = port.isValidPerson(_isValidPerson_employeeCode, _isValidPerson_dateTime, _isValidPerson_requestState, _isValidPerson_leaveHour);
        System.out.println("isValidPerson.result=" + _isValidPerson__return);


        }
        {
        System.out.println("Invoking getOrganizationChartIdByEmployeeById...");
        long _getOrganizationChartIdByEmployeeById_regionId = 0;
        long _getOrganizationChartIdByEmployeeById_employeeId = 0;
        java.lang.Long _getOrganizationChartIdByEmployeeById__return = port.getOrganizationChartIdByEmployeeById(_getOrganizationChartIdByEmployeeById_regionId, _getOrganizationChartIdByEmployeeById_employeeId);
        System.out.println("getOrganizationChartIdByEmployeeById.result=" + _getOrganizationChartIdByEmployeeById__return);


        }
        {
        System.out.println("Invoking getAllExtraWorkPermissionsByDate...");
        java.lang.String _getAllExtraWorkPermissionsByDate_date = "";
        ir.imi.testwebcard.domain.soap.ArrayOfDailyExtraWorkPermissionDataModel _getAllExtraWorkPermissionsByDate__return = port.getAllExtraWorkPermissionsByDate(_getAllExtraWorkPermissionsByDate_date);
        System.out.println("getAllExtraWorkPermissionsByDate.result=" + _getAllExtraWorkPermissionsByDate__return);


        }
        {
        System.out.println("Invoking getDailyMissionsOrVacations...");
        javax.xml.datatype.XMLGregorianCalendar _getDailyMissionsOrVacations_startDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _getDailyMissionsOrVacations_endDateTime = null;
        java.lang.String _getDailyMissionsOrVacations__return = port.getDailyMissionsOrVacations(_getDailyMissionsOrVacations_startDateTime, _getDailyMissionsOrVacations_endDateTime);
        System.out.println("getDailyMissionsOrVacations.result=" + _getDailyMissionsOrVacations__return);


        }
        {
        System.out.println("Invoking getAllEmployeesInfo...");
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo _getAllEmployeesInfo__return = port.getAllEmployeesInfo();
        System.out.println("getAllEmployeesInfo.result=" + _getAllEmployeesInfo__return);


        }
        {
        System.out.println("Invoking addMissionRegistration...");
        java.lang.String _addMissionRegistration_employeeCode = "";
        long _addMissionRegistration_missionId = 0;
        javax.xml.datatype.XMLGregorianCalendar _addMissionRegistration_beginDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addMissionRegistration_endDateTime = null;
        java.lang.String _addMissionRegistration__return = port.addMissionRegistration(_addMissionRegistration_employeeCode, _addMissionRegistration_missionId, _addMissionRegistration_beginDateTime, _addMissionRegistration_endDateTime);
        System.out.println("addMissionRegistration.result=" + _addMissionRegistration__return);


        }
        {
        System.out.println("Invoking getIoSources...");
        ir.imi.testwebcard.domain.soap.ArrayOfString _getIoSources__return = port.getIoSources();
        System.out.println("getIoSources.result=" + _getIoSources__return);


        }
        {
        System.out.println("Invoking getEmployeeFullNameFromLoginResult...");
        java.lang.String _getEmployeeFullNameFromLoginResult_userName = "";
        java.lang.String _getEmployeeFullNameFromLoginResult_password = "";
        java.lang.String _getEmployeeFullNameFromLoginResult__return = port.getEmployeeFullNameFromLoginResult(_getEmployeeFullNameFromLoginResult_userName, _getEmployeeFullNameFromLoginResult_password);
        System.out.println("getEmployeeFullNameFromLoginResult.result=" + _getEmployeeFullNameFromLoginResult__return);


        }
        {
        System.out.println("Invoking getUiRequestCartableIds...");
        java.lang.String _getUiRequestCartableIds_employeeCode = "";
        ir.imi.testwebcard.domain.soap.UiRequestCartableIds _getUiRequestCartableIds__return = port.getUiRequestCartableIds(_getUiRequestCartableIds_employeeCode);
        System.out.println("getUiRequestCartableIds.result=" + _getUiRequestCartableIds__return);


        }
        {
        System.out.println("Invoking getCalendarWorkDayTypesByEmployee...");
        java.lang.String _getCalendarWorkDayTypesByEmployee_employeeCode = "";
        java.lang.String _getCalendarWorkDayTypesByEmployee_fromDate = "";
        java.lang.String _getCalendarWorkDayTypesByEmployee_toDate = "";
        ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto _getCalendarWorkDayTypesByEmployee__return = port.getCalendarWorkDayTypesByEmployee(_getCalendarWorkDayTypesByEmployee_employeeCode, _getCalendarWorkDayTypesByEmployee_fromDate, _getCalendarWorkDayTypesByEmployee_toDate);
        System.out.println("getCalendarWorkDayTypesByEmployee.result=" + _getCalendarWorkDayTypesByEmployee__return);


        }
        {
        System.out.println("Invoking getAllEmployeesWithOrgId...");
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo _getAllEmployeesWithOrgId__return = port.getAllEmployeesWithOrgId();
        System.out.println("getAllEmployeesWithOrgId.result=" + _getAllEmployeesWithOrgId__return);


        }
        {
        System.out.println("Invoking getAllPeriodFunctionalityWinPayList...");
        java.lang.String _getAllPeriodFunctionalityWinPayList_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getAllPeriodFunctionalityWinPayList_date = null;
        boolean _getAllPeriodFunctionalityWinPayList_withVacation = false;
        boolean _getAllPeriodFunctionalityWinPayList_withSequenceWorkingDetails = false;
        boolean _getAllPeriodFunctionalityWinPayList_withSpecialExtraWork = false;
        boolean _getAllPeriodFunctionalityWinPayList_withVacationRemaining = false;
        boolean _getAllPeriodFunctionalityWinPayList_withSpecialAddSubVacation = false;
        boolean _getAllPeriodFunctionalityWinPayList_withMission = false;
        ir.imi.testwebcard.domain.soap.ArrayOfPeriodCalculationInfo _getAllPeriodFunctionalityWinPayList__return = port.getAllPeriodFunctionalityWinPayList(_getAllPeriodFunctionalityWinPayList_employeeCode, _getAllPeriodFunctionalityWinPayList_date, _getAllPeriodFunctionalityWinPayList_withVacation, _getAllPeriodFunctionalityWinPayList_withSequenceWorkingDetails, _getAllPeriodFunctionalityWinPayList_withSpecialExtraWork, _getAllPeriodFunctionalityWinPayList_withVacationRemaining, _getAllPeriodFunctionalityWinPayList_withSpecialAddSubVacation, _getAllPeriodFunctionalityWinPayList_withMission);
        System.out.println("getAllPeriodFunctionalityWinPayList.result=" + _getAllPeriodFunctionalityWinPayList__return);


        }
        {
        System.out.println("Invoking getOrganizationChartList...");
        long _getOrganizationChartList_regionId = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfString _getOrganizationChartList__return = port.getOrganizationChartList(_getOrganizationChartList_regionId);
        System.out.println("getOrganizationChartList.result=" + _getOrganizationChartList__return);


        }
        {
        System.out.println("Invoking getValidCardList...");
        long _getValidCardList_regionId = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfString _getValidCardList__return = port.getValidCardList(_getValidCardList_regionId);
        System.out.println("getValidCardList.result=" + _getValidCardList__return);


        }
        {
        System.out.println("Invoking getAllVacationRegistrationsByDate...");
        java.lang.String _getAllVacationRegistrationsByDate_date = "";
        ir.imi.testwebcard.domain.soap.ArrayOfVacationRegistrationDataModel _getAllVacationRegistrationsByDate__return = port.getAllVacationRegistrationsByDate(_getAllVacationRegistrationsByDate_date);
        System.out.println("getAllVacationRegistrationsByDate.result=" + _getAllVacationRegistrationsByDate__return);


        }
        {
        System.out.println("Invoking getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId...");
        long _getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId_currentOrganizationchartId = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel _getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId__return = port.getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId(_getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId_currentOrganizationchartId);
        System.out.println("getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId.result=" + _getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId__return);


        }
        {
        System.out.println("Invoking getAllMissionRegistrationsByDate...");
        java.lang.String _getAllMissionRegistrationsByDate_date = "";
        ir.imi.testwebcard.domain.soap.ArrayOfMissionRegistrationDataModel _getAllMissionRegistrationsByDate__return = port.getAllMissionRegistrationsByDate(_getAllMissionRegistrationsByDate_date);
        System.out.println("getAllMissionRegistrationsByDate.result=" + _getAllMissionRegistrationsByDate__return);


        }
        {
        System.out.println("Invoking getIoRecordInDayByEmployeeCode...");
        java.lang.String _getIoRecordInDayByEmployeeCode_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getIoRecordInDayByEmployeeCode_dayDate = null;
        ir.imi.testwebcard.domain.soap.ArrayOfStaffIOs _getIoRecordInDayByEmployeeCode__return = port.getIoRecordInDayByEmployeeCode(_getIoRecordInDayByEmployeeCode_employeeCode, _getIoRecordInDayByEmployeeCode_dayDate);
        System.out.println("getIoRecordInDayByEmployeeCode.result=" + _getIoRecordInDayByEmployeeCode__return);


        }
        {
        System.out.println("Invoking checkTimeAttendanceSystemHasThirdPartyWebServicec...");
        boolean _checkTimeAttendanceSystemHasThirdPartyWebServicec__return = port.checkTimeAttendanceSystemHasThirdPartyWebServicec();
        System.out.println("checkTimeAttendanceSystemHasThirdPartyWebServicec.result=" + _checkTimeAttendanceSystemHasThirdPartyWebServicec__return);


        }
        {
        System.out.println("Invoking getAllOrganizationChartList...");
        ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel _getAllOrganizationChartList__return = port.getAllOrganizationChartList();
        System.out.println("getAllOrganizationChartList.result=" + _getAllOrganizationChartList__return);


        }
        {
        System.out.println("Invoking getAllEmployees...");
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _getAllEmployees__return = port.getAllEmployees();
        System.out.println("getAllEmployees.result=" + _getAllEmployees__return);


        }
        {
        System.out.println("Invoking getRemainUiEmployeeVacationTypeRepositoryList...");
        java.lang.String _getRemainUiEmployeeVacationTypeRepositoryList_employeeCode = "";
        long _getRemainUiEmployeeVacationTypeRepositoryList_currentWorkingYear = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfString _getRemainUiEmployeeVacationTypeRepositoryList__return = port.getRemainUiEmployeeVacationTypeRepositoryList(_getRemainUiEmployeeVacationTypeRepositoryList_employeeCode, _getRemainUiEmployeeVacationTypeRepositoryList_currentWorkingYear);
        System.out.println("getRemainUiEmployeeVacationTypeRepositoryList.result=" + _getRemainUiEmployeeVacationTypeRepositoryList__return);


        }
        {
        System.out.println("Invoking getAllSpecialExtraWorksByPeriodId...");
        long _getAllSpecialExtraWorksByPeriodId_periodId = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfSpecialExtraWorkDataModel _getAllSpecialExtraWorksByPeriodId__return = port.getAllSpecialExtraWorksByPeriodId(_getAllSpecialExtraWorksByPeriodId_periodId);
        System.out.println("getAllSpecialExtraWorksByPeriodId.result=" + _getAllSpecialExtraWorksByPeriodId__return);


        }
        {
        System.out.println("Invoking getEmployeeCodeByKeyNumber...");
        java.lang.String _getEmployeeCodeByKeyNumber_keyNumber = "";
        java.lang.String _getEmployeeCodeByKeyNumber_gregorianDate = "";
        java.lang.String _getEmployeeCodeByKeyNumber_shamsiDate = "";
        ir.imi.testwebcard.domain.soap.SystemModuleType _getEmployeeCodeByKeyNumber_systemType = null;
        ir.imi.testwebcard.domain.soap.UiDeviceModuleType _getEmployeeCodeByKeyNumber_deviceModuleType = null;
        java.lang.String _getEmployeeCodeByKeyNumber__return = port.getEmployeeCodeByKeyNumber(_getEmployeeCodeByKeyNumber_keyNumber, _getEmployeeCodeByKeyNumber_gregorianDate, _getEmployeeCodeByKeyNumber_shamsiDate, _getEmployeeCodeByKeyNumber_systemType, _getEmployeeCodeByKeyNumber_deviceModuleType);
        System.out.println("getEmployeeCodeByKeyNumber.result=" + _getEmployeeCodeByKeyNumber__return);


        }
        {
        System.out.println("Invoking getIsExitOverTimeList...");
        java.lang.String _getIsExitOverTimeList_perno = "";
        java.lang.String _getIsExitOverTimeList_time = "";
        javax.xml.datatype.XMLGregorianCalendar _getIsExitOverTimeList_startDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getIsExitOverTimeList_endDate = null;
        boolean _getIsExitOverTimeList__return = port.getIsExitOverTimeList(_getIsExitOverTimeList_perno, _getIsExitOverTimeList_time, _getIsExitOverTimeList_startDate, _getIsExitOverTimeList_endDate);
        System.out.println("getIsExitOverTimeList.result=" + _getIsExitOverTimeList__return);


        }
        {
        System.out.println("Invoking getOrganizationChartIdByEmployee...");
        long _getOrganizationChartIdByEmployee_regionId = 0;
        long _getOrganizationChartIdByEmployee_employeeId = 0;
        long _getOrganizationChartIdByEmployee__return = port.getOrganizationChartIdByEmployee(_getOrganizationChartIdByEmployee_regionId, _getOrganizationChartIdByEmployee_employeeId);
        System.out.println("getOrganizationChartIdByEmployee.result=" + _getOrganizationChartIdByEmployee__return);


        }
        {
        System.out.println("Invoking getDayCalculationInfo...");
        java.lang.String _getDayCalculationInfo_employeeCode = "";
        javax.xml.datatype.XMLGregorianCalendar _getDayCalculationInfo_fromDate = null;
        javax.xml.datatype.XMLGregorianCalendar _getDayCalculationInfo_toDate = null;
        port.getDayCalculationInfo(_getDayCalculationInfo_employeeCode, _getDayCalculationInfo_fromDate, _getDayCalculationInfo_toDate);


        }
        {
        System.out.println("Invoking getListOfEmployeeEvents...");
        ir.imi.testwebcard.domain.soap.EmployeeEventType _getListOfEmployeeEvents_employeeEvent = null;
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _getListOfEmployeeEvents__return = port.getListOfEmployeeEvents(_getListOfEmployeeEvents_employeeEvent);
        System.out.println("getListOfEmployeeEvents.result=" + _getListOfEmployeeEvents__return);


        }
        {
        System.out.println("Invoking addVacationRegistration...");
        java.lang.String _addVacationRegistration_employeeCode = "";
        long _addVacationRegistration_vacationId = 0;
        javax.xml.datatype.XMLGregorianCalendar _addVacationRegistration_beginDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addVacationRegistration_endDateTime = null;
        java.lang.String _addVacationRegistration__return = port.addVacationRegistration(_addVacationRegistration_employeeCode, _addVacationRegistration_vacationId, _addVacationRegistration_beginDateTime, _addVacationRegistration_endDateTime);
        System.out.println("addVacationRegistration.result=" + _addVacationRegistration__return);


        }
        {
        System.out.println("Invoking getAllCurrentlyEmployees...");
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _getAllCurrentlyEmployees__return = port.getAllCurrentlyEmployees();
        System.out.println("getAllCurrentlyEmployees.result=" + _getAllCurrentlyEmployees__return);


        }
        {
        System.out.println("Invoking getAllEmployeesOfOneOrganizationChartWithAllSubsets...");
        long _getAllEmployeesOfOneOrganizationChartWithAllSubsets_currentOrganizationchartId = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel _getAllEmployeesOfOneOrganizationChartWithAllSubsets__return = port.getAllEmployeesOfOneOrganizationChartWithAllSubsets(_getAllEmployeesOfOneOrganizationChartWithAllSubsets_currentOrganizationchartId);
        System.out.println("getAllEmployeesOfOneOrganizationChartWithAllSubsets.result=" + _getAllEmployeesOfOneOrganizationChartWithAllSubsets__return);


        }
        {
        System.out.println("Invoking getIORecordAfterId...");
        long _getIORecordAfterId_id = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _getIORecordAfterId__return = port.getIORecordAfterId(_getIORecordAfterId_id);
        System.out.println("getIORecordAfterId.result=" + _getIORecordAfterId__return);


        }
        {
        System.out.println("Invoking isPresent...");
        long _isPresent_id = 0;
        javax.xml.datatype.XMLGregorianCalendar _isPresent_dateTime = null;
        boolean _isPresent__return = port.isPresent(_isPresent_id, _isPresent_dateTime);
        System.out.println("isPresent.result=" + _isPresent__return);


        }
        {
        System.out.println("Invoking getDevicePersons...");
        java.util.List<java.lang.String> _getDevicePersons_deviceModuleType = null;
        ir.imi.testwebcard.domain.soap.ArrayOfDevicePerson _getDevicePersons__return = port.getDevicePersons(_getDevicePersons_deviceModuleType);
        System.out.println("getDevicePersons.result=" + _getDevicePersons__return);


        }
        {
        System.out.println("Invoking getAllIoRecordsByDate...");
        java.lang.String _getAllIoRecordsByDate_date = "";
        ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _getAllIoRecordsByDate__return = port.getAllIoRecordsByDate(_getAllIoRecordsByDate_date);
        System.out.println("getAllIoRecordsByDate.result=" + _getAllIoRecordsByDate__return);


        }
        {
        System.out.println("Invoking getUiRequestCartableCount...");
        java.lang.String _getUiRequestCartableCount_employeeCode = "";
        java.lang.String _getUiRequestCartableCount__return = port.getUiRequestCartableCount(_getUiRequestCartableCount_employeeCode);
        System.out.println("getUiRequestCartableCount.result=" + _getUiRequestCartableCount__return);


        }
        {
        System.out.println("Invoking getRemainUiEmployeeVacationTypeRepository...");
        java.lang.String _getRemainUiEmployeeVacationTypeRepository_employeeCode = "";
        long _getRemainUiEmployeeVacationTypeRepository_vacationtypeId = 0;
        java.lang.String _getRemainUiEmployeeVacationTypeRepository__return = port.getRemainUiEmployeeVacationTypeRepository(_getRemainUiEmployeeVacationTypeRepository_employeeCode, _getRemainUiEmployeeVacationTypeRepository_vacationtypeId);
        System.out.println("getRemainUiEmployeeVacationTypeRepository.result=" + _getRemainUiEmployeeVacationTypeRepository__return);


        }
        {
        System.out.println("Invoking getAllValidEmployeeRange...");
        javax.xml.datatype.XMLGregorianCalendar _getAllValidEmployeeRange_dateTime = null;
        int _getAllValidEmployeeRange_requestState = 0;
        ir.imi.testwebcard.domain.soap.ArrayOfValidEmployeeRange _getAllValidEmployeeRange__return = port.getAllValidEmployeeRange(_getAllValidEmployeeRange_dateTime, _getAllValidEmployeeRange_requestState);
        System.out.println("getAllValidEmployeeRange.result=" + _getAllValidEmployeeRange__return);


        }
        {
        System.out.println("Invoking getIORecordPerDateRange...");
        java.lang.String _getIORecordPerDateRange_fromDate = "";
        java.lang.String _getIORecordPerDateRange_toDate = "";
        ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel _getIORecordPerDateRange__return = port.getIORecordPerDateRange(_getIORecordPerDateRange_fromDate, _getIORecordPerDateRange_toDate);
        System.out.println("getIORecordPerDateRange.result=" + _getIORecordPerDateRange__return);


        }
        {
        System.out.println("Invoking getCalendarWorkDayTypes...");
        java.lang.String _getCalendarWorkDayTypes_calendarName = "";
        java.lang.String _getCalendarWorkDayTypes_fromDate = "";
        java.lang.String _getCalendarWorkDayTypes_toDate = "";
        ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto _getCalendarWorkDayTypes__return = port.getCalendarWorkDayTypes(_getCalendarWorkDayTypes_calendarName, _getCalendarWorkDayTypes_fromDate, _getCalendarWorkDayTypes_toDate);
        System.out.println("getCalendarWorkDayTypes.result=" + _getCalendarWorkDayTypes__return);


        }
        {
        System.out.println("Invoking addMissionRegistrationEx...");
        java.lang.String _addMissionRegistrationEx_employeeCode = "";
        java.lang.String _addMissionRegistrationEx_confirmEmployeeCode = "";
        long _addMissionRegistrationEx_missionId = 0;
        javax.xml.datatype.XMLGregorianCalendar _addMissionRegistrationEx_beginDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addMissionRegistrationEx_endDateTime = null;
        java.lang.String _addMissionRegistrationEx_missionLocationName = "";
        java.lang.String _addMissionRegistrationEx__return = port.addMissionRegistrationEx(_addMissionRegistrationEx_employeeCode, _addMissionRegistrationEx_confirmEmployeeCode, _addMissionRegistrationEx_missionId, _addMissionRegistrationEx_beginDateTime, _addMissionRegistrationEx_endDateTime, _addMissionRegistrationEx_missionLocationName);
        System.out.println("addMissionRegistrationEx.result=" + _addMissionRegistrationEx__return);


        }
        {
        System.out.println("Invoking addVacationRegistrationPermission...");
        java.lang.String _addVacationRegistrationPermission_employeeCode = "";
        long _addVacationRegistrationPermission_vacationId = 0;
        javax.xml.datatype.XMLGregorianCalendar _addVacationRegistrationPermission_beginDateTime = null;
        javax.xml.datatype.XMLGregorianCalendar _addVacationRegistrationPermission_endDateTime = null;
        java.lang.String _addVacationRegistrationPermission_vacationRequestReason = "";
        java.lang.String _addVacationRegistrationPermission_description = "";
        java.lang.String _addVacationRegistrationPermission__return = port.addVacationRegistrationPermission(_addVacationRegistrationPermission_employeeCode, _addVacationRegistrationPermission_vacationId, _addVacationRegistrationPermission_beginDateTime, _addVacationRegistrationPermission_endDateTime, _addVacationRegistrationPermission_vacationRequestReason, _addVacationRegistrationPermission_description);
        System.out.println("addVacationRegistrationPermission.result=" + _addVacationRegistrationPermission__return);


        }
        {
        System.out.println("Invoking persistIoRecrd...");
        java.lang.String _persistIoRecrd_keyNumber = "";
        javax.xml.datatype.XMLGregorianCalendar _persistIoRecrd_ioDateTime = null;
        long _persistIoRecrd_deviceModuleType = 0;
        long _persistIoRecrd_hadwareCode = 0;
        boolean _persistIoRecrd__return = port.persistIoRecrd(_persistIoRecrd_keyNumber, _persistIoRecrd_ioDateTime, _persistIoRecrd_deviceModuleType, _persistIoRecrd_hadwareCode);
        System.out.println("persistIoRecrd.result=" + _persistIoRecrd__return);


        }
        {
        System.out.println("Invoking getTimeAttendancePcCheckByEmployeeCode...");
        java.lang.String _getTimeAttendancePcCheckByEmployeeCode_employeeCode = "";
        java.lang.String _getTimeAttendancePcCheckByEmployeeCode_dateTime = "";
        javax.xml.ws.Holder<java.lang.Boolean> _getTimeAttendancePcCheckByEmployeeCode_getTimeAttendancePcCheckByEmployeeCodeResult = new javax.xml.ws.Holder<java.lang.Boolean>();
        javax.xml.ws.Holder<java.lang.String> _getTimeAttendancePcCheckByEmployeeCode_reason = new javax.xml.ws.Holder<java.lang.String>();
        port.getTimeAttendancePcCheckByEmployeeCode(_getTimeAttendancePcCheckByEmployeeCode_employeeCode, _getTimeAttendancePcCheckByEmployeeCode_dateTime, _getTimeAttendancePcCheckByEmployeeCode_getTimeAttendancePcCheckByEmployeeCodeResult, _getTimeAttendancePcCheckByEmployeeCode_reason);

        System.out.println("getTimeAttendancePcCheckByEmployeeCode._getTimeAttendancePcCheckByEmployeeCode_getTimeAttendancePcCheckByEmployeeCodeResult=" + _getTimeAttendancePcCheckByEmployeeCode_getTimeAttendancePcCheckByEmployeeCodeResult.value);
        System.out.println("getTimeAttendancePcCheckByEmployeeCode._getTimeAttendancePcCheckByEmployeeCode_reason=" + _getTimeAttendancePcCheckByEmployeeCode_reason.value);

        }

        System.exit(0);
    }

}
