package ir.imi.testwebcard.domain.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.5
 * 2025-01-08T14:55:54.011+03:30
 * Generated source version: 3.6.5
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "EtsGeneralDataProviderServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EtsGeneralDataProviderServiceSoap {

    @WebMethod(operationName = "AddSpecialExtraWorkPermission", action = "http://tempuri.org/AddSpecialExtraWorkPermission")
    @RequestWrapper(localName = "AddSpecialExtraWorkPermission", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddSpecialExtraWorkPermission")
    @ResponseWrapper(localName = "AddSpecialExtraWorkPermissionResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddSpecialExtraWorkPermissionResponse")
    @WebResult(name = "AddSpecialExtraWorkPermissionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addSpecialExtraWorkPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        int value,
        @WebParam(name = "periodId", targetNamespace = "http://tempuri.org/")
        long periodId,
        @WebParam(name = "requestReason", targetNamespace = "http://tempuri.org/")
        java.lang.String requestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        java.lang.String description,
        @WebParam(name = "specialExtraWorkId", targetNamespace = "http://tempuri.org/")
        long specialExtraWorkId,
        @WebParam(name = "organizationChartId", targetNamespace = "http://tempuri.org/")
        long organizationChartId
    );

    @WebMethod(operationName = "AddMissionRegistrationPermission", action = "http://tempuri.org/AddMissionRegistrationPermission")
    @RequestWrapper(localName = "AddMissionRegistrationPermission", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddMissionRegistrationPermission")
    @ResponseWrapper(localName = "AddMissionRegistrationPermissionResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddMissionRegistrationPermissionResponse")
    @WebResult(name = "AddMissionRegistrationPermissionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addMissionRegistrationPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "missionId", targetNamespace = "http://tempuri.org/")
        long missionId,
        @WebParam(name = "missionLocationId", targetNamespace = "http://tempuri.org/")
        long missionLocationId,
        @WebParam(name = "missionSubject", targetNamespace = "http://tempuri.org/")
        java.lang.String missionSubject,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "requestReason", targetNamespace = "http://tempuri.org/")
        java.lang.String requestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        java.lang.String description
    );

    @WebMethod(operationName = "IsValidPersonStringDate", action = "http://tempuri.org/IsValidPersonStringDate")
    @RequestWrapper(localName = "IsValidPersonStringDate", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsValidPersonStringDate")
    @ResponseWrapper(localName = "IsValidPersonStringDateResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsValidPersonStringDateResponse")
    @WebResult(name = "IsValidPersonStringDateResult", targetNamespace = "http://tempuri.org/")
    public boolean isValidPersonStringDate(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        java.lang.String dateTime,
        @WebParam(name = "requestState", targetNamespace = "http://tempuri.org/")
        int requestState
    );

    @WebMethod(operationName = "Test", action = "http://tempuri.org/Test")
    @RequestWrapper(localName = "Test", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.TestResponse")
    @WebResult(name = "TestResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String test()
;

    @WebMethod(operationName = "GetIORecordPerPersistOn", action = "http://tempuri.org/GetIORecordPerPersistOn")
    @RequestWrapper(localName = "GetIORecordPerPersistOn", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIORecordPerPersistOn")
    @ResponseWrapper(localName = "GetIORecordPerPersistOnResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIORecordPerPersistOnResponse")
    @WebResult(name = "GetIORecordPerPersistOnResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getIORecordPerPersistOn(

        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        java.lang.String toDate
    );

    @WebMethod(operationName = "GetFunctionalityList", action = "http://tempuri.org/GetFunctionalityList")
    @RequestWrapper(localName = "GetFunctionalityList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetFunctionalityList")
    @ResponseWrapper(localName = "GetFunctionalityListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetFunctionalityListResponse")
    @WebResult(name = "GetFunctionalityListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfString getFunctionalityList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "AddDailyExtraWorkPermission", action = "http://tempuri.org/AddDailyExtraWorkPermission")
    @RequestWrapper(localName = "AddDailyExtraWorkPermission", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddDailyExtraWorkPermission")
    @ResponseWrapper(localName = "AddDailyExtraWorkPermissionResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddDailyExtraWorkPermissionResponse")
    @WebResult(name = "AddDailyExtraWorkPermissionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addDailyExtraWorkPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "extraWorkId", targetNamespace = "http://tempuri.org/")
        long extraWorkId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "requestReason", targetNamespace = "http://tempuri.org/")
        java.lang.String requestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        java.lang.String description
    );

    @WebMethod(operationName = "GetFunctionalityWinPayList", action = "http://tempuri.org/GetFunctionalityWinPayList")
    @RequestWrapper(localName = "GetFunctionalityWinPayList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetFunctionalityWinPayList")
    @ResponseWrapper(localName = "GetFunctionalityWinPayListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetFunctionalityWinPayListResponse")
    @WebResult(name = "GetFunctionalityWinPayListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.PeriodCalculationInfo getFunctionalityWinPayList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "withVacation", targetNamespace = "http://tempuri.org/")
        boolean withVacation,
        @WebParam(name = "withSequenceWorkingDetails", targetNamespace = "http://tempuri.org/")
        boolean withSequenceWorkingDetails,
        @WebParam(name = "withSpecialExtraWork", targetNamespace = "http://tempuri.org/")
        boolean withSpecialExtraWork,
        @WebParam(name = "withVacationRemaining", targetNamespace = "http://tempuri.org/")
        boolean withVacationRemaining,
        @WebParam(name = "withSpecialAddSubVacation", targetNamespace = "http://tempuri.org/")
        boolean withSpecialAddSubVacation,
        @WebParam(name = "withMission", targetNamespace = "http://tempuri.org/")
        boolean withMission
    );

    @WebMethod(operationName = "GetAllCurrentlyEmployeesWithKey", action = "http://tempuri.org/GetAllCurrentlyEmployeesWithKey")
    @RequestWrapper(localName = "GetAllCurrentlyEmployeesWithKey", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllCurrentlyEmployeesWithKey")
    @ResponseWrapper(localName = "GetAllCurrentlyEmployeesWithKeyResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllCurrentlyEmployeesWithKeyResponse")
    @WebResult(name = "GetAllCurrentlyEmployeesWithKeyResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModelWithKey getAllCurrentlyEmployeesWithKey()
;

    @WebMethod(operationName = "GetPeriodCalculationInfo", action = "http://tempuri.org/GetPeriodCalculationInfo")
    @RequestWrapper(localName = "GetPeriodCalculationInfo", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetPeriodCalculationInfo")
    @ResponseWrapper(localName = "GetPeriodCalculationInfoResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetPeriodCalculationInfoResponse")
    public void getPeriodCalculationInfo(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "IsValidReserve", action = "http://tempuri.org/IsValidReserve")
    @RequestWrapper(localName = "IsValidReserve", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsValidReserve")
    @ResponseWrapper(localName = "IsValidReserveResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsValidReserveResponse")
    @WebResult(name = "IsValidReserveResult", targetNamespace = "http://tempuri.org/")
    public boolean isValidReserve(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "startDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar startDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "officialHolidaySetting", targetNamespace = "http://tempuri.org/")
        java.lang.String officialHolidaySetting,
        @WebParam(name = "agreedHolidaySetting", targetNamespace = "http://tempuri.org/")
        java.lang.String agreedHolidaySetting,
        @WebParam(name = "normalDaySetting", targetNamespace = "http://tempuri.org/")
        java.lang.String normalDaySetting,
        @WebParam(name = "chekExtraWorkPermission", targetNamespace = "http://tempuri.org/")
        boolean chekExtraWorkPermission
    );

    @WebMethod(operationName = "IsValidPerson", action = "http://tempuri.org/IsValidPerson")
    @RequestWrapper(localName = "IsValidPerson", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsValidPerson")
    @ResponseWrapper(localName = "IsValidPersonResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsValidPersonResponse")
    @WebResult(name = "IsValidPersonResult", targetNamespace = "http://tempuri.org/")
    public boolean isValidPerson(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dateTime,
        @WebParam(name = "requestState", targetNamespace = "http://tempuri.org/")
        int requestState,
        @WebParam(name = "leaveHour", targetNamespace = "http://tempuri.org/")
        java.lang.String leaveHour
    );

    @WebMethod(operationName = "GetOrganizationChartIdByEmployeeById", action = "http://tempuri.org/GetOrganizationChartIdByEmployeeById")
    @RequestWrapper(localName = "GetOrganizationChartIdByEmployeeById", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetOrganizationChartIdByEmployeeById")
    @ResponseWrapper(localName = "GetOrganizationChartIdByEmployeeByIdResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetOrganizationChartIdByEmployeeByIdResponse")
    @WebResult(name = "GetOrganizationChartIdByEmployeeByIdResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Long getOrganizationChartIdByEmployeeById(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId,
        @WebParam(name = "employeeId", targetNamespace = "http://tempuri.org/")
        long employeeId
    );

    @WebMethod(operationName = "GetAllExtraWorkPermissionsByDate", action = "http://tempuri.org/GetAllExtraWorkPermissionsByDate")
    @RequestWrapper(localName = "GetAllExtraWorkPermissionsByDate", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllExtraWorkPermissionsByDate")
    @ResponseWrapper(localName = "GetAllExtraWorkPermissionsByDateResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllExtraWorkPermissionsByDateResponse")
    @WebResult(name = "GetAllExtraWorkPermissionsByDateResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfDailyExtraWorkPermissionDataModel getAllExtraWorkPermissionsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "GetDailyMissionsOrVacations", action = "http://tempuri.org/GetDailyMissionsOrVacations")
    @RequestWrapper(localName = "GetDailyMissionsOrVacations", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetDailyMissionsOrVacations")
    @ResponseWrapper(localName = "GetDailyMissionsOrVacationsResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetDailyMissionsOrVacationsResponse")
    @WebResult(name = "GetDailyMissionsOrVacationsResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getDailyMissionsOrVacations(

        @WebParam(name = "startDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar startDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime
    );

    @WebMethod(operationName = "GetAllEmployeesInfo", action = "http://tempuri.org/GetAllEmployeesInfo")
    @RequestWrapper(localName = "GetAllEmployeesInfo", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesInfo")
    @ResponseWrapper(localName = "GetAllEmployeesInfoResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesInfoResponse")
    @WebResult(name = "GetAllEmployeesInfoResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo getAllEmployeesInfo()
;

    @WebMethod(operationName = "AddMissionRegistration", action = "http://tempuri.org/AddMissionRegistration")
    @RequestWrapper(localName = "AddMissionRegistration", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddMissionRegistration")
    @ResponseWrapper(localName = "AddMissionRegistrationResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddMissionRegistrationResponse")
    @WebResult(name = "AddMissionRegistrationResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addMissionRegistration(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "missionId", targetNamespace = "http://tempuri.org/")
        long missionId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime
    );

    @WebMethod(operationName = "GetIoSources", action = "http://tempuri.org/GetIoSources")
    @RequestWrapper(localName = "GetIoSources", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIoSources")
    @ResponseWrapper(localName = "GetIoSourcesResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIoSourcesResponse")
    @WebResult(name = "GetIoSourcesResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfString getIoSources()
;

    @WebMethod(operationName = "GetEmployeeFullNameFromLoginResult", action = "http://tempuri.org/GetEmployeeFullNameFromLoginResult")
    @RequestWrapper(localName = "GetEmployeeFullNameFromLoginResult", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetEmployeeFullNameFromLoginResult")
    @ResponseWrapper(localName = "GetEmployeeFullNameFromLoginResultResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetEmployeeFullNameFromLoginResultResponse")
    @WebResult(name = "GetEmployeeFullNameFromLoginResultResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getEmployeeFullNameFromLoginResult(

        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebMethod(operationName = "GetUiRequestCartableIds", action = "http://tempuri.org/GetUiRequestCartableIds")
    @RequestWrapper(localName = "GetUiRequestCartableIds", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetUiRequestCartableIds")
    @ResponseWrapper(localName = "GetUiRequestCartableIdsResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetUiRequestCartableIdsResponse")
    @WebResult(name = "GetUiRequestCartableIdsResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.UiRequestCartableIds getUiRequestCartableIds(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode
    );

    @WebMethod(operationName = "GetCalendarWorkDayTypesByEmployee", action = "http://tempuri.org/GetCalendarWorkDayTypesByEmployee")
    @RequestWrapper(localName = "GetCalendarWorkDayTypesByEmployee", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetCalendarWorkDayTypesByEmployee")
    @ResponseWrapper(localName = "GetCalendarWorkDayTypesByEmployeeResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetCalendarWorkDayTypesByEmployeeResponse")
    @WebResult(name = "GetCalendarWorkDayTypesByEmployeeResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto getCalendarWorkDayTypesByEmployee(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        java.lang.String toDate
    );

    @WebMethod(operationName = "GetAllEmployeesWithOrgId", action = "http://tempuri.org/GetAllEmployeesWithOrgId")
    @RequestWrapper(localName = "GetAllEmployeesWithOrgId", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesWithOrgId")
    @ResponseWrapper(localName = "GetAllEmployeesWithOrgIdResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesWithOrgIdResponse")
    @WebResult(name = "GetAllEmployeesWithOrgIdResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeInfo getAllEmployeesWithOrgId()
;

    @WebMethod(operationName = "GetAllPeriodFunctionalityWinPayList", action = "http://tempuri.org/GetAllPeriodFunctionalityWinPayList")
    @RequestWrapper(localName = "GetAllPeriodFunctionalityWinPayList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllPeriodFunctionalityWinPayList")
    @ResponseWrapper(localName = "GetAllPeriodFunctionalityWinPayListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllPeriodFunctionalityWinPayListResponse")
    @WebResult(name = "GetAllPeriodFunctionalityWinPayListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfPeriodCalculationInfo getAllPeriodFunctionalityWinPayList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar date,
        @WebParam(name = "withVacation", targetNamespace = "http://tempuri.org/")
        boolean withVacation,
        @WebParam(name = "withSequenceWorkingDetails", targetNamespace = "http://tempuri.org/")
        boolean withSequenceWorkingDetails,
        @WebParam(name = "withSpecialExtraWork", targetNamespace = "http://tempuri.org/")
        boolean withSpecialExtraWork,
        @WebParam(name = "withVacationRemaining", targetNamespace = "http://tempuri.org/")
        boolean withVacationRemaining,
        @WebParam(name = "withSpecialAddSubVacation", targetNamespace = "http://tempuri.org/")
        boolean withSpecialAddSubVacation,
        @WebParam(name = "withMission", targetNamespace = "http://tempuri.org/")
        boolean withMission
    );

    @WebMethod(operationName = "GetOrganizationChartList", action = "http://tempuri.org/GetOrganizationChartList")
    @RequestWrapper(localName = "GetOrganizationChartList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetOrganizationChartList")
    @ResponseWrapper(localName = "GetOrganizationChartListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetOrganizationChartListResponse")
    @WebResult(name = "GetOrganizationChartListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfString getOrganizationChartList(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId
    );

    @WebMethod(operationName = "GetValidCardList", action = "http://tempuri.org/GetValidCardList")
    @RequestWrapper(localName = "GetValidCardList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetValidCardList")
    @ResponseWrapper(localName = "GetValidCardListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetValidCardListResponse")
    @WebResult(name = "GetValidCardListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfString getValidCardList(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId
    );

    @WebMethod(operationName = "GetAllVacationRegistrationsByDate", action = "http://tempuri.org/GetAllVacationRegistrationsByDate")
    @RequestWrapper(localName = "GetAllVacationRegistrationsByDate", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllVacationRegistrationsByDate")
    @ResponseWrapper(localName = "GetAllVacationRegistrationsByDateResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllVacationRegistrationsByDateResponse")
    @WebResult(name = "GetAllVacationRegistrationsByDateResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfVacationRegistrationDataModel getAllVacationRegistrationsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId", action = "http://tempuri.org/GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId")
    @RequestWrapper(localName = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId")
    @ResponseWrapper(localName = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgIdResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgIdResponse")
    @WebResult(name = "GetAllSubsetOrganizationChartsWithEmployeesByCurrentOrgIdResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel getAllSubsetOrganizationChartsWithEmployeesByCurrentOrgId(

        @WebParam(name = "currentOrganizationchartId", targetNamespace = "http://tempuri.org/")
        long currentOrganizationchartId
    );

    @WebMethod(operationName = "GetAllMissionRegistrationsByDate", action = "http://tempuri.org/GetAllMissionRegistrationsByDate")
    @RequestWrapper(localName = "GetAllMissionRegistrationsByDate", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllMissionRegistrationsByDate")
    @ResponseWrapper(localName = "GetAllMissionRegistrationsByDateResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllMissionRegistrationsByDateResponse")
    @WebResult(name = "GetAllMissionRegistrationsByDateResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfMissionRegistrationDataModel getAllMissionRegistrationsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "GetIoRecordInDayByEmployeeCode", action = "http://tempuri.org/GetIoRecordInDayByEmployeeCode")
    @RequestWrapper(localName = "GetIoRecordInDayByEmployeeCode", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIoRecordInDayByEmployeeCode")
    @ResponseWrapper(localName = "GetIoRecordInDayByEmployeeCodeResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIoRecordInDayByEmployeeCodeResponse")
    @WebResult(name = "GetIoRecordInDayByEmployeeCodeResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfStaffIOs getIoRecordInDayByEmployeeCode(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "DayDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dayDate
    );

    @WebMethod(operationName = "CheckTimeAttendanceSystemHasThirdPartyWebServicec", action = "http://tempuri.org/CheckTimeAttendanceSystemHasThirdPartyWebServicec")
    @RequestWrapper(localName = "CheckTimeAttendanceSystemHasThirdPartyWebServicec", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.CheckTimeAttendanceSystemHasThirdPartyWebServicec")
    @ResponseWrapper(localName = "CheckTimeAttendanceSystemHasThirdPartyWebServicecResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.CheckTimeAttendanceSystemHasThirdPartyWebServicecResponse")
    @WebResult(name = "CheckTimeAttendanceSystemHasThirdPartyWebServicecResult", targetNamespace = "http://tempuri.org/")
    public boolean checkTimeAttendanceSystemHasThirdPartyWebServicec()
;

    @WebMethod(operationName = "GetAllOrganizationChartList", action = "http://tempuri.org/GetAllOrganizationChartList")
    @RequestWrapper(localName = "GetAllOrganizationChartList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllOrganizationChartList")
    @ResponseWrapper(localName = "GetAllOrganizationChartListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllOrganizationChartListResponse")
    @WebResult(name = "GetAllOrganizationChartListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfOrganizationChartDataModel getAllOrganizationChartList()
;

    @WebMethod(operationName = "GetAllEmployees", action = "http://tempuri.org/GetAllEmployees")
    @RequestWrapper(localName = "GetAllEmployees", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployees")
    @ResponseWrapper(localName = "GetAllEmployeesResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesResponse")
    @WebResult(name = "GetAllEmployeesResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getAllEmployees()
;

    @WebMethod(operationName = "GetRemainUiEmployeeVacationTypeRepositoryList", action = "http://tempuri.org/GetRemainUiEmployeeVacationTypeRepositoryList")
    @RequestWrapper(localName = "GetRemainUiEmployeeVacationTypeRepositoryList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetRemainUiEmployeeVacationTypeRepositoryList")
    @ResponseWrapper(localName = "GetRemainUiEmployeeVacationTypeRepositoryListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetRemainUiEmployeeVacationTypeRepositoryListResponse")
    @WebResult(name = "GetRemainUiEmployeeVacationTypeRepositoryListResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfString getRemainUiEmployeeVacationTypeRepositoryList(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "CurrentWorkingYear", targetNamespace = "http://tempuri.org/")
        long currentWorkingYear
    );

    @WebMethod(operationName = "GetAllSpecialExtraWorksByPeriodId", action = "http://tempuri.org/GetAllSpecialExtraWorksByPeriodId")
    @RequestWrapper(localName = "GetAllSpecialExtraWorksByPeriodId", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllSpecialExtraWorksByPeriodId")
    @ResponseWrapper(localName = "GetAllSpecialExtraWorksByPeriodIdResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllSpecialExtraWorksByPeriodIdResponse")
    @WebResult(name = "GetAllSpecialExtraWorksByPeriodIdResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfSpecialExtraWorkDataModel getAllSpecialExtraWorksByPeriodId(

        @WebParam(name = "periodId", targetNamespace = "http://tempuri.org/")
        long periodId
    );

    @WebMethod(operationName = "GetEmployeeCodeByKeyNumber", action = "http://tempuri.org/GetEmployeeCodeByKeyNumber")
    @RequestWrapper(localName = "GetEmployeeCodeByKeyNumber", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetEmployeeCodeByKeyNumber")
    @ResponseWrapper(localName = "GetEmployeeCodeByKeyNumberResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetEmployeeCodeByKeyNumberResponse")
    @WebResult(name = "GetEmployeeCodeByKeyNumberResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getEmployeeCodeByKeyNumber(

        @WebParam(name = "keyNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String keyNumber,
        @WebParam(name = "gregorianDate", targetNamespace = "http://tempuri.org/")
        java.lang.String gregorianDate,
        @WebParam(name = "shamsiDate", targetNamespace = "http://tempuri.org/")
        java.lang.String shamsiDate,
        @WebParam(name = "systemType", targetNamespace = "http://tempuri.org/")
        ir.imi.testwebcard.domain.soap.SystemModuleType systemType,
        @WebParam(name = "deviceModuleType", targetNamespace = "http://tempuri.org/")
        ir.imi.testwebcard.domain.soap.UiDeviceModuleType deviceModuleType
    );

    @WebMethod(operationName = "GetIsExitOverTimeList", action = "http://tempuri.org/GetIsExitOverTimeList")
    @RequestWrapper(localName = "GetIsExitOverTimeList", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIsExitOverTimeList")
    @ResponseWrapper(localName = "GetIsExitOverTimeListResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIsExitOverTimeListResponse")
    @WebResult(name = "GetIsExitOverTimeListResult", targetNamespace = "http://tempuri.org/")
    public boolean getIsExitOverTimeList(

        @WebParam(name = "perno", targetNamespace = "http://tempuri.org/")
        java.lang.String perno,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        java.lang.String time,
        @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDate
    );

    @WebMethod(operationName = "GetOrganizationChartIdByEmployee", action = "http://tempuri.org/GetOrganizationChartIdByEmployee")
    @RequestWrapper(localName = "GetOrganizationChartIdByEmployee", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetOrganizationChartIdByEmployee")
    @ResponseWrapper(localName = "GetOrganizationChartIdByEmployeeResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetOrganizationChartIdByEmployeeResponse")
    @WebResult(name = "GetOrganizationChartIdByEmployeeResult", targetNamespace = "http://tempuri.org/")
    public long getOrganizationChartIdByEmployee(

        @WebParam(name = "regionId", targetNamespace = "http://tempuri.org/")
        long regionId,
        @WebParam(name = "employeeId", targetNamespace = "http://tempuri.org/")
        long employeeId
    );

    @WebMethod(operationName = "GetDayCalculationInfo", action = "http://tempuri.org/GetDayCalculationInfo")
    @RequestWrapper(localName = "GetDayCalculationInfo", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetDayCalculationInfo")
    @ResponseWrapper(localName = "GetDayCalculationInfoResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetDayCalculationInfoResponse")
    public void getDayCalculationInfo(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar toDate
    );

    @WebMethod(operationName = "GetListOfEmployeeEvents", action = "http://tempuri.org/GetListOfEmployeeEvents")
    @RequestWrapper(localName = "GetListOfEmployeeEvents", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetListOfEmployeeEvents")
    @ResponseWrapper(localName = "GetListOfEmployeeEventsResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetListOfEmployeeEventsResponse")
    @WebResult(name = "GetListOfEmployeeEventsResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getListOfEmployeeEvents(

        @WebParam(name = "employeeEvent", targetNamespace = "http://tempuri.org/")
        ir.imi.testwebcard.domain.soap.EmployeeEventType employeeEvent
    );

    @WebMethod(operationName = "AddVacationRegistration", action = "http://tempuri.org/AddVacationRegistration")
    @RequestWrapper(localName = "AddVacationRegistration", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddVacationRegistration")
    @ResponseWrapper(localName = "AddVacationRegistrationResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddVacationRegistrationResponse")
    @WebResult(name = "AddVacationRegistrationResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addVacationRegistration(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "vacationId", targetNamespace = "http://tempuri.org/")
        long vacationId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime
    );

    @WebMethod(operationName = "GetAllCurrentlyEmployees", action = "http://tempuri.org/GetAllCurrentlyEmployees")
    @RequestWrapper(localName = "GetAllCurrentlyEmployees", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllCurrentlyEmployees")
    @ResponseWrapper(localName = "GetAllCurrentlyEmployeesResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllCurrentlyEmployeesResponse")
    @WebResult(name = "GetAllCurrentlyEmployeesResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getAllCurrentlyEmployees()
;

    @WebMethod(operationName = "GetAllEmployeesOfOneOrganizationChartWithAllSubsets", action = "http://tempuri.org/GetAllEmployeesOfOneOrganizationChartWithAllSubsets")
    @RequestWrapper(localName = "GetAllEmployeesOfOneOrganizationChartWithAllSubsets", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesOfOneOrganizationChartWithAllSubsets")
    @ResponseWrapper(localName = "GetAllEmployeesOfOneOrganizationChartWithAllSubsetsResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllEmployeesOfOneOrganizationChartWithAllSubsetsResponse")
    @WebResult(name = "GetAllEmployeesOfOneOrganizationChartWithAllSubsetsResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfEmployeeDataModel getAllEmployeesOfOneOrganizationChartWithAllSubsets(

        @WebParam(name = "currentOrganizationchartId", targetNamespace = "http://tempuri.org/")
        long currentOrganizationchartId
    );

    @WebMethod(operationName = "GetIORecordAfterId", action = "http://tempuri.org/GetIORecordAfterId")
    @RequestWrapper(localName = "GetIORecordAfterId", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIORecordAfterId")
    @ResponseWrapper(localName = "GetIORecordAfterIdResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIORecordAfterIdResponse")
    @WebResult(name = "GetIORecordAfterIdResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getIORecordAfterId(

        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        long id
    );

    @WebMethod(operationName = "IsPresent", action = "http://tempuri.org/IsPresent")
    @RequestWrapper(localName = "IsPresent", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsPresent")
    @ResponseWrapper(localName = "IsPresentResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.IsPresentResponse")
    @WebResult(name = "IsPresentResult", targetNamespace = "http://tempuri.org/")
    public boolean isPresent(

        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        long id,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dateTime
    );

    @WebMethod(operationName = "GetDevicePersons", action = "http://tempuri.org/GetDevicePersons")
    @RequestWrapper(localName = "GetDevicePersons", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetDevicePersons")
    @ResponseWrapper(localName = "GetDevicePersonsResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetDevicePersonsResponse")
    @WebResult(name = "GetDevicePersonsResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfDevicePerson getDevicePersons(

        @WebParam(name = "deviceModuleType", targetNamespace = "http://tempuri.org/")
        java.util.List<java.lang.String> deviceModuleType
    );

    @WebMethod(operationName = "GetAllIoRecordsByDate", action = "http://tempuri.org/GetAllIoRecordsByDate")
    @RequestWrapper(localName = "GetAllIoRecordsByDate", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllIoRecordsByDate")
    @ResponseWrapper(localName = "GetAllIoRecordsByDateResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllIoRecordsByDateResponse")
    @WebResult(name = "GetAllIoRecordsByDateResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getAllIoRecordsByDate(

        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        java.lang.String date
    );

    @WebMethod(operationName = "GetUiRequestCartableCount", action = "http://tempuri.org/GetUiRequestCartableCount")
    @RequestWrapper(localName = "GetUiRequestCartableCount", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetUiRequestCartableCount")
    @ResponseWrapper(localName = "GetUiRequestCartableCountResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetUiRequestCartableCountResponse")
    @WebResult(name = "GetUiRequestCartableCountResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getUiRequestCartableCount(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode
    );

    @WebMethod(operationName = "GetRemainUiEmployeeVacationTypeRepository", action = "http://tempuri.org/GetRemainUiEmployeeVacationTypeRepository")
    @RequestWrapper(localName = "GetRemainUiEmployeeVacationTypeRepository", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetRemainUiEmployeeVacationTypeRepository")
    @ResponseWrapper(localName = "GetRemainUiEmployeeVacationTypeRepositoryResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetRemainUiEmployeeVacationTypeRepositoryResponse")
    @WebResult(name = "GetRemainUiEmployeeVacationTypeRepositoryResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getRemainUiEmployeeVacationTypeRepository(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "vacationtypeId", targetNamespace = "http://tempuri.org/")
        long vacationtypeId
    );

    @WebMethod(operationName = "GetAllValidEmployeeRange", action = "http://tempuri.org/GetAllValidEmployeeRange")
    @RequestWrapper(localName = "GetAllValidEmployeeRange", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllValidEmployeeRange")
    @ResponseWrapper(localName = "GetAllValidEmployeeRangeResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetAllValidEmployeeRangeResponse")
    @WebResult(name = "GetAllValidEmployeeRangeResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfValidEmployeeRange getAllValidEmployeeRange(

        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dateTime,
        @WebParam(name = "requestState", targetNamespace = "http://tempuri.org/")
        int requestState
    );

    @WebMethod(operationName = "GetIORecordPerDateRange", action = "http://tempuri.org/GetIORecordPerDateRange")
    @RequestWrapper(localName = "GetIORecordPerDateRange", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIORecordPerDateRange")
    @ResponseWrapper(localName = "GetIORecordPerDateRangeResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetIORecordPerDateRangeResponse")
    @WebResult(name = "GetIORecordPerDateRangeResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfIoRecordDataModel getIORecordPerDateRange(

        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        java.lang.String toDate
    );

    @WebMethod(operationName = "GetCalendarWorkDayTypes", action = "http://tempuri.org/GetCalendarWorkDayTypes")
    @RequestWrapper(localName = "GetCalendarWorkDayTypes", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetCalendarWorkDayTypes")
    @ResponseWrapper(localName = "GetCalendarWorkDayTypesResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetCalendarWorkDayTypesResponse")
    @WebResult(name = "GetCalendarWorkDayTypesResult", targetNamespace = "http://tempuri.org/")
    public ir.imi.testwebcard.domain.soap.ArrayOfCalendarDayListDto getCalendarWorkDayTypes(

        @WebParam(name = "calendarName", targetNamespace = "http://tempuri.org/")
        java.lang.String calendarName,
        @WebParam(name = "fromDate", targetNamespace = "http://tempuri.org/")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://tempuri.org/")
        java.lang.String toDate
    );

    @WebMethod(operationName = "AddMissionRegistrationEx", action = "http://tempuri.org/AddMissionRegistrationEx")
    @RequestWrapper(localName = "AddMissionRegistrationEx", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddMissionRegistrationEx")
    @ResponseWrapper(localName = "AddMissionRegistrationExResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddMissionRegistrationExResponse")
    @WebResult(name = "AddMissionRegistrationExResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addMissionRegistrationEx(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "confirmEmployeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String confirmEmployeeCode,
        @WebParam(name = "missionId", targetNamespace = "http://tempuri.org/")
        long missionId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "missionLocationName", targetNamespace = "http://tempuri.org/")
        java.lang.String missionLocationName
    );

    @WebMethod(operationName = "AddVacationRegistrationPermission", action = "http://tempuri.org/AddVacationRegistrationPermission")
    @RequestWrapper(localName = "AddVacationRegistrationPermission", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddVacationRegistrationPermission")
    @ResponseWrapper(localName = "AddVacationRegistrationPermissionResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.AddVacationRegistrationPermissionResponse")
    @WebResult(name = "AddVacationRegistrationPermissionResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String addVacationRegistrationPermission(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "vacationId", targetNamespace = "http://tempuri.org/")
        long vacationId,
        @WebParam(name = "beginDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDateTime,
        @WebParam(name = "endDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDateTime,
        @WebParam(name = "vacationRequestReason", targetNamespace = "http://tempuri.org/")
        java.lang.String vacationRequestReason,
        @WebParam(name = "description", targetNamespace = "http://tempuri.org/")
        java.lang.String description
    );

    @WebMethod(operationName = "PersistIoRecrd", action = "http://tempuri.org/PersistIoRecrd")
    @RequestWrapper(localName = "PersistIoRecrd", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.PersistIoRecrd")
    @ResponseWrapper(localName = "PersistIoRecrdResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.PersistIoRecrdResponse")
    @WebResult(name = "PersistIoRecrdResult", targetNamespace = "http://tempuri.org/")
    public boolean persistIoRecrd(

        @WebParam(name = "keyNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String keyNumber,
        @WebParam(name = "ioDateTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar ioDateTime,
        @WebParam(name = "deviceModuleType", targetNamespace = "http://tempuri.org/")
        long deviceModuleType,
        @WebParam(name = "hadwareCode", targetNamespace = "http://tempuri.org/")
        long hadwareCode
    );

    @WebMethod(operationName = "GetTimeAttendancePcCheckByEmployeeCode", action = "http://tempuri.org/GetTimeAttendancePcCheckByEmployeeCode")
    @RequestWrapper(localName = "GetTimeAttendancePcCheckByEmployeeCode", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetTimeAttendancePcCheckByEmployeeCode")
    @ResponseWrapper(localName = "GetTimeAttendancePcCheckByEmployeeCodeResponse", targetNamespace = "http://tempuri.org/", className = "ir.imi.testwebcard.domain.soap.GetTimeAttendancePcCheckByEmployeeCodeResponse")
    public void getTimeAttendancePcCheckByEmployeeCode(

        @WebParam(name = "employeeCode", targetNamespace = "http://tempuri.org/")
        java.lang.String employeeCode,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        java.lang.String dateTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetTimeAttendancePcCheckByEmployeeCodeResult", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.Boolean> getTimeAttendancePcCheckByEmployeeCodeResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "reason", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> reason
    );
}
